cpu:
    cache: {
        location: /tmp/my_app,
        max_files: 100,
    }
    banner: default banner
    threads: 1


programs: [C:/Users/Rocil/eclipse-workspace/multiplex/examples/train/train.py, C:/Users/Rocil/eclipse-workspace/multiplex/examples/test/test.py]


argparse:
    - name_or_flags: log_path
      type: str
      default: False
      nargs: '?'
      help: 'specify a log file to use'

    - name_or_flags: ['-s', '--seed']
      type: int
      default: 0
      help: 'random seed for reproducibility'
      dest: seed
      choices: [0, -1, 1]

    - name_or_flags: ['-f', '--load']
      dest: 'load_path'
      type: str
      default: False
      metavar: file
      help: 'load model from a .pth file'

    - name_or_flags: ['-v', '--validate']
      action: 'store_true'
      help: 'find validation loss on model'


#"name_or_flags", "action", "nargs", "const", "default", "type", "choices", "required", "help", "metavar", "dest"