argparse:
  parser:
    description: 'Training tool for an MNIST network'
  arguments:
    - name_or_flags: ['--batch-size']
      type: int
      default: 64
      metavar: 'N'
      help: 'input batch size for training (default: 64)'
    - name_or_flags: ['--epochs']
      type: int
      default: 14
      metavar: 'N'
      help: 'number of epochs to train (default: 14)'
    - name_or_flags: ['--log-interval']
      type: int
      default: 10
      metavar: 'N'
      help: 'how many batches to wait before logging training status'
    - name_or_flags: ['--save-model']
      action: 'store_true'
      default: False
      help: 'For Saving the current Model'